config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2
  get 'manifest', to: 'manifest#show', as: :manifest, defaults: { format: 'application/manifest+json' }

  get 'accounts/:id', to: 'accounts#show', as: :network_account

  get :design, to: 'static#design'

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  resource :feed, defaults: { format: 'atom' } do
    get :hot, to: 'stories#index'
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  namespace :dashboard do
    resource :followed_accounts, only: [:show] do
      get :recent, on: :member
    end
  end

  resources :stories, path: :posts do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      namespace :markdown do
        get :preview
      end

      resources :stories, only: [] do
        post :toggle_like, on: :member
        post :scrap, on: :member
        delete :destroy, on: :member, as: :delete
      end

      resources :comments, only: [:new, :create, :edit, :update, :destroy] do
        post :toggle_like, on: :member
      end

      resources :accounts, only: [] do
        post :toggle_follow, on: :member
      end
    end

    namespace :v1, defaults: { format: :json } do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
    resources :accounts, except: [:delete] do
      post :suspend, on: :member
      post :silence, on: :member
      post :unsilence, on: :member
    end
    resources :domain_blocks, except: [:edit, :update]
    resources :flags, except: [:new, :create, :delete] do
      post :resolve, on: :member
      post :unresolve, on: :member
    end
  end
end

app/views/shared/_flash.html.slim
.flashes(data-controller="flashes")
  - flash.each do |severity, value|
    .flashes-item(
      data-severity=severity
      data-value=value
      data-target="flashes.item"
    )

app/views/shared/_follow_btn.html.slim
a.btn-n.btn-n-sm.btn-n-primary(
  class=presenter.root_class
  data-controller="follow-btn"
  data-follow-btn-action-path=toggle_follow_api_ujs_account_path(presenter.account)
  data-follow-btn-following=presenter.following?.to_s
  data-follow-btn-username=presenter.account.username
  data-action="click->follow-btn#toggle"
)

  i.fe.mr-2(class=presenter.icon_class)
  = presenter.label

app/views/shared/_footer.html.slim
footer.text-center
  p #{t('.powered_by')} <a href="https://gitlab.com/mbajur/prismo"><span>△</span> Prismo</a> #{Prismo::Version}

app/views/shared/_head.html.slim
meta(name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no")
link(rel="apple-touch-icon" sizes="180x180" href="/ios.png")
meta(name="current-account-id" content=current_account&.id)
link(id="favicon" rel="icon" href="/favicon.png" type="image/png" sizes="32x32" data-controller="favicon")
link(rel="manifest" href=manifest_path(format: :json))

app/views/shared/_markdown_editor.html.slim
- placeholder ||= ''
- additional_input_targets ||= []
- additional_preview_classes ||= []
- targets = (['markdown-editor.input'] + additional_input_targets).compact.join(' ')

.markdown-editor(data-controller="markdown-editor")
  .markdown-editor-body
    .markdown-editor-body-pane.markdown-editor-body-input.active(data-target="markdown-editor.editor")
      = form.text_area name, class: 'form-input',
                             placeholder: placeholder,
                             data: { target: targets }

    .markdown-editor-body-pane.markdown-editor-body-preview(data-target="markdown-editor.preview" class=additional_preview_classes)
      p = t('.nothing_to_show')

  .markdown-editor-footer
    a(href="https://simplemde.com/markdown-guide" target="_blank")
      = t('.markdown_supported')

    a.float-right(href="#" data-action="markdown-editor#togglePreview")
      = t('.toggle_preview')

app/views/shared/_navbar.html+phone.slim
header.navbar-main
  .container
    .navbar
      section.navbar-section
        = render 'shared/_navbar/jumpbox'

      section.navbar-section
        = active_link_to new_story_path, class: 'btn btn-link' do
          i.fe.fe-plus-circle

        - if user_signed_in?
          = render 'shared/_navbar/notifications'
          = render 'shared/_navbar/profile'
        - else
          = active_link_to new_user_session_path, class: 'btn btn-link' do
            i.fe.fe-user

app/views/shared/_navbar.html.slim
header.navbar-main
  .container
    .navbar
      section.navbar-section
        = link_to Setting.site_title, root_path, class: 'navbar-brand'
        = render 'shared/_navbar/jumpbox'

      section.navbar-section
        = active_link_to t('.add_story'), new_story_path, class: 'btn btn-link'

        - if user_signed_in?
          = render 'shared/_navbar/notifications'
          = render 'shared/_navbar/profile'
        - else
          = link_to t('.join_us'), new_user_session_path, class: 'btn btn-link'

app/views/shared/_popular_tags.html.slim
- tags = TagsQuery.new.popular.first(10).map(&:decorate)

.box-n.mb-3.popular-tags
  .box-n-body.p-2
    ul.list-inline
      - tags.each do |tag|
        li.list-inline-item
          a(href=tag.path) ##{tag.name}

app/views/shared/_sentry.erb
<% if ENV.key?('SENTRY_DSN_FE') %>
  <script src="https://cdn.ravenjs.com/3.19.1/raven.min.js" crossorigin="anonymous"></script>
<% end %>