config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.is_admin? } do
    mount Sidekiq::Web, at: 'admin/sidekiq', as: :sidekiq
  end

  devise_for :users, path: 'auth', controllers: {
    # omniauth_callbacks: 'auth/omniauth_callbacks',
    # sessions:           'auth/sessions',
    registrations:      'auth/registrations',
    # passwords:          'auth/passwords',
    # confirmations:      'auth/confirmations',
  }

  root to: 'stories#index'

  get '.well-known/host-meta', to: 'well_known/host_meta#show', as: :host_meta, defaults: { format: 'xml' }
  get '.well-known/webfinger', to: 'well_known/webfinger#show', as: :webfinger
  get '.well-known/x-nodeinfo2', to: 'well_known/nodeinfo2#show', as: :nodeinfo2
  get 'manifest', to: 'manifest#show', as: :manifest, defaults: { format: 'application/manifest+json' }

  get 'accounts/:id', to: 'accounts#show', as: :network_account

  get :design, to: 'static#design'

  resource :account, path: '@:username' do
    root to: 'accounts/stories#hot'
    get :recent, to: 'accounts/stories#recent', as: :recent_stories

    resources :comments, only: [] do
      root to: 'accounts/comments#hot'
      get :recent, on: :collection, controller: 'accounts/comments'
    end
  end

  resource :feed, defaults: { format: 'atom' } do
    get :hot, to: 'stories#index'
  end

  get '/stories/:id', to: redirect('/posts/%{id}')

  namespace :dashboard do
    resource :followed_accounts, only: [:show] do
      get :recent, on: :member
    end
  end

  resources :stories, path: :posts do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :tags, param: :name, only: [] do
    resources :stories, path: '/', controller: 'tags/stories', only: [] do
      get '/', action: :hot, on: :collection
      get :recent, on: :collection
    end
  end

  resources :comments, only: [:index, :show] do
    get :recent, on: :collection

    resource :flag, only: %i[new create edit update]
  end

  resources :notifications, only: [:index] do
    get :unread, on: :collection
  end

  get '/ap/accounts/:username', to: redirect('/@%{username}')
  get '/ap/stories/:id', to: redirect('/stories/%{id}')
  get '/ap/comments/:id', to: redirect('/comments/%{id}')

  namespace :activitypub, path: :ap do
    resources :accounts, only: [], param: :username do
      get :outbox, on: :member

      resource :inbox, only: [:create], controller: 'account/inbox'
    end
  end

  namespace :api do
    # Salmon
    post '/salmon/:id', to: 'salmon#update', as: :salmon

    namespace :ujs do
      namespace :markdown do
        get :preview
      end

      resources :stories, only: [] do
        post :toggle_like, on: :member
        post :scrap, on: :member
        delete :destroy, on: :member, as: :delete
      end

      resources :comments, only: [:new, :create, :edit, :update, :destroy] do
        post :toggle_like, on: :member
      end

      resources :accounts, only: [] do
        post :toggle_follow, on: :member
      end
    end

    namespace :v1, defaults: { format: :json } do
      post 'tools/scrap_url', controller: :tools, action: :scrap_url

      resources :notifications, only: [] do
        get :unread_count, on: :collection
      end

      resources :tags, only: [:index]
    end
  end

  namespace :settings do
    resource :profile, only: [:show, :update]
  end

  namespace :admin do
    resource :settings, only: [:edit, :update]
    resources :accounts, except: [:delete] do
      post :suspend, on: :member
      post :silence, on: :member
      post :unsilence, on: :member
    end
    resources :domain_blocks, except: [:edit, :update]
    resources :flags, except: [:new, :create, :delete] do
      post :resolve, on: :member
      post :unresolve, on: :member
    end
  end
end

app/views/shared/_navbar/_jumpbox.html.slim
- jumpbox = Jumpbox.instance
- current_link = current_jumpbox_link

.dropdown.jumpbox(
  title=current_link
  data-controller="jumpbox dropdown"
  data-dropdown-placement="bottom-start"
)
  a.btn.btn-link(
    data-target="dropdown.toggle"
    data-action="click->dropdown#toggle click@window->dropdown#hide"
    href="#"
    title=current_link
  )
    .tile.tile-centered
      .tile-icon
        - if current_link.media_type == :icon
          i(class=current_link.media_class)
        - elsif current_link.media_type == :avatar
          img.avatar.avatar-xs(src=current_link.media)

      .tile-content
        = current_link

  ul.menu-n(data-target="dropdown.dropdown" style="min-width: 210px")
    li.menu-n__divider(data-content="Prismo feeds")

    - jumpbox.prismo_feeds.each do |link|
      - next if link.opts[:auth_required] && !user_signed_in?

      li.menu-n__item
        = active_link_to link.path, link.link_opts do
          .tile
            .tile-icon
              i(class=link.media_class)
            .tile-content
              = link.label

app/views/shared/_navbar/_notifications.html.slim
a.btn.btn-link.navbar-main-notifications#notifications-indicator(
  href=notifications_path
  data-controller="notifications-indicator"
  data-turbolinks-permanent=true
  data-notifications-indicator-all-path=notifications_path
  data-notifications-indicator-unread-path=unread_notifications_path
  title="Notifications"
)
  i.fe.fe-bell

app/views/shared/_navbar/_profile.html.slim
.dropdown.dropdown-right.navbar-main-profile(
  data-controller="dropdown"
  data-dropdown-placement="bottom-end"
)
  a.btn.btn-link(href="javascript:void(0);" data-target="dropdown.toggle" data-action="click->dropdown#toggle click@window->dropdown#hide")
    = image_tag current_account.avatar_url(:size_60), class: 'avatar'

  ul.menu-n(data-target="dropdown.dropdown" style="min-width: 200px")
    li.menu-n__item
      .tile.tile-centered
        .tile-icon
          = image_tag current_account.avatar_url(:size_60), class: 'avatar'
        .tile-content = current_account

    li.menu-n__divider
    li.menu-n__item
      = link_to 'My Profile', current_account.path
    li.menu-n__item
      = link_to 'Settings', settings_profile_path

    - if current_user.is_admin?
      li.menu-n__item
        = link_to 'Admin', edit_admin_settings_path

    li.menu-n__divider
    li.menu-n__item
      = link_to 'Sign-out', destroy_user_session_path, data: { method: "delete" }